### ISSUE TITLE
Program

### ISSUE THREAD

**Issue by C-Erastus** [nr1333/python-class#3]
Write a program that uses a for loop to print the numbers from 0 to 9. Write a paragraph about you approach

**Comment by nr1333** [comment]
for i in range(10):
     print(i)

From the numbers in range from 1 - 0, the program prints out the numbers up to 9 because the number 10 does not specify if it should be equal to 10. Printing 'i' will print out numbers from 0, 1, 2, 3, 4, 5, 6, 7, 8, 9.
